name: CI

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install server dependencies
        run: cd server && npm ci
      - name: Run backend tests
        run: cd server && npm test
      - name: Install client dependencies
        run: cd client && npm ci
      - name: Run frontend tests
        run: cd client && npm test
